<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6FIB2UL" failures="0" tests="7" name="testScripts.LoginTest" time="21.247" errors="1" timestamp="2025-10-17T15:59:37 CEST" skipped="2">
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithValidCredentials" time="5.196"/>
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithValidUserNameInvalidPassword" time="2.398">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidUserNameInvalidPassword -->
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithValidUserNameInvalidPassword" time="2.774">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidUserNameInvalidPassword -->
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithValidUserNameInvalidPassword" time="2.223">
    <error message="Cannot invoke &quot;org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)&quot; because &quot;r&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" because "r" is null
at utilities.ExcelUtility.getStringData(ExcelUtility.java:30)
at testScripts.LoginTest.verifyLoginWithValidUserNameInvalidPassword(LoginTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyLoginWithValidUserNameInvalidPassword -->
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithInvalidUserNameValidPassword" time="2.932"/>
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithInvalidUserNameInvalidPassword" time="2.975"/>
  <testcase classname="testScripts.LoginTest" name="verifyLoginWithInvalidUserNameInvalidPassword" time="2.749"/>
</testsuite> <!-- testScripts.LoginTest -->
